"""Khoi tao CSDL thu vien so

Revision ID: 81565560a0d3
Revises: 
Create Date: 2026-10-08 16:42:06.249495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81565560a0d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=150), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=100), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('publishers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=150), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.UnicodeText(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Unicode(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.Unicode(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.UnicodeText(), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(length=200), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('publisher_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('publish_year', sa.Integer(), nullable=True),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('keywords', sa.Unicode(length=255), nullable=True),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('image', sa.Unicode(length=500), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('available', sa.Integer(), nullable=False),
    sa.Column('access_level', sa.String(length=10), nullable=False),
    sa.Column('allow_download', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('available >= 0 AND available <= quantity', name='ck_books_available'),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_books_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_books_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_books_publish_year'), ['publish_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_books_publisher_id'), ['publisher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_books_title'), ['title'], unique=False)
        batch_op.create_index('uq_books_isbn', ['isbn'], unique=True, mssql_where=sa.text('isbn IS NOT NULL'), sqlite_where=sa.text('isbn IS NOT NULL'))

    op.create_table('book_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.UnicodeText(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_review_rating'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'user_id', name='uq_review_book_user')
    )
    op.create_table('borrowing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('borrow_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('fine_amount', sa.Integer(), nullable=False),
    sa.Column('fine_paid', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.UnicodeText(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('borrowing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_borrowing_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_borrowing_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_borrowing_user_id'), ['user_id'], unique=False)

    op.create_table('document_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.Unicode(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=100), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_name')
    )
    with op.batch_alter_table('document_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_files_book_id'), ['book_id'], unique=False)

    op.create_table('access_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Unicode(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['document_files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_logs_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_logs_user_id'), ['user_id'], unique=False)

    op.create_table('borrow_renewals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borrow_id', sa.Integer(), nullable=False),
    sa.Column('old_due_date', sa.Date(), nullable=False),
    sa.Column('new_due_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['borrow_id'], ['borrowing.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('borrow_renewals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_borrow_renewals_borrow_id'), ['borrow_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow_renewals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_borrow_renewals_borrow_id'))

    op.drop_table('borrow_renewals')
    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_access_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_access_logs_book_id'))
        batch_op.drop_index(batch_op.f('ix_access_logs_action'))

    op.drop_table('access_logs')
    with op.batch_alter_table('document_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_files_book_id'))

    op.drop_table('document_files')
    with op.batch_alter_table('borrowing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_borrowing_user_id'))
        batch_op.drop_index(batch_op.f('ix_borrowing_status'))
        batch_op.drop_index(batch_op.f('ix_borrowing_book_id'))

    op.drop_table('borrowing')
    op.drop_table('book_reviews')
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index('uq_books_isbn', mssql_where=sa.text('isbn IS NOT NULL'), sqlite_where=sa.text('isbn IS NOT NULL'))
        batch_op.drop_index(batch_op.f('ix_books_title'))
        batch_op.drop_index(batch_op.f('ix_books_publisher_id'))
        batch_op.drop_index(batch_op.f('ix_books_publish_year'))
        batch_op.drop_index(batch_op.f('ix_books_category_id'))
        batch_op.drop_index(batch_op.f('ix_books_author_id'))

    op.drop_table('books')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('publishers')
    op.drop_table('categories')
    op.drop_table('authors')
    # ### end Alembic commands ###
